services:
  postgres:
    image: 'postgres:latest'
    container_name: 'blackjack-db'
    environment:
      - 'POSTGRES_DB=blackjack'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: