@startuml
title Component Diagram - Blackjack
left to right direction
json JSON {
}
[RESTful API]

component Application {
portin p_api

[GameLogic]
[Statistics]
[Rules]

portout p_db
}

database "PostgreSQL" {
}

JSON --> [RESTful API]
[RESTful API] --> p_api
p_db --> "PostgreSQL"

@enduml
