@startuml
title API Endpoint /api/blackjack/stats/overview

actor User

participant "Controller\n(Rest Adapter)" as Controller
participant "EmitStatsService\n(Use Case)" as Service
participant "StatsCalculator" as Calculator
participant "JpaRepositoryAdapter\n(Outbound Port)" as Adapter
database PostgresSQL as DB

== Request Overview Stats ==

User -> Controller : GET /api/blackjack/stats/overview
Controller -> Service : emitStats(overviewQuery)
Service -> Adapter : retrieveOverviewData()
Adapter -> DB : SQL Queries

alt resources found
    DB --> Adapter : Overview data
    Adapter --> Service : Overview data
    Service -> Calculator : calculateOverviewStats(Data)
    Calculator --> Service : OverviewStats
    Service --> Controller : OverviewStats
    Controller --> User : 200 OK + OverviewStats JSON

else resources not found
    DB --> Adapter : Not Found
    Adapter --> Service : Failure (404)
    Service --> Controller : Failure (404)
    Controller --> User : 404 Not Found + Error message
end
@enduml
