@startuml
title API Endpoint /api/blackjack/stats/user/{userId}

actor User

participant "Controller\n(Rest Adapter)" as Controller
participant "EmitStatsService\n(Use Case)" as Service
participant "StatsCalculator" as Calculator
participant "JpaRepositoryAdapter\n(Outbound Port)" as Adapter
database PostgresSQL as DB

== Request User Stats ==

User -> Controller : GET /api/blackjack/stats/user/{userId}
Controller -> Service : emitStats(userQuery)
Service -> Adapter : retrieveUserStats(userId)
Adapter -> DB : SQL Query

alt user resources found
    DB --> Adapter : User Data
    Adapter --> Service : User Data
    Service -> Calculator : calculateOverviewStats(Data)
    Calculator --> Service : UserStats
    Service --> Controller : UserStats
    Controller --> User : 200 OK + UserStats JSON

else user resources not found
    DB --> Adapter : Not Found
    Adapter --> Service : Failure (404)
    Service --> Controller : Failure (404)
    Controller --> User : 404 Not Found + Error message
end
@enduml
