@startuml sequence_diagram_rules
title API Endpoint /api/blackjack/rules
actor Player

participant "Controller\n(Rest Adapter)" as Controller
participant "RulesService\n(Use Case)" as Service
participant "FileRulesAdapter\n(Outbound Port)" as Adapter
database PostgresSQL

== Request General Rules ==

    Player --> Controller : GET /api/blackjack/rules
    Controller --> Service : emitRules(query)
    Service --> Adapter : retrieveRules(GENERAL)
    Adapter --> PostgresSQL : SQL Query

alt resource found

    PostgresSQL --> Adapter : Rules
    Adapter --> Service : Rules
    Service --> Controller : Result
    Controller --> Player : 200 OK + Response

else resource not found
    PostgresSQL --> Adapter : not found
    Adapter --> Service : error
    Service --> Controller : error
    Controller --> Player : 404 Not Found

end

@enduml