@startuml
title API Endpoint /api/blackjack/chances/{gameId}
actor Player

participant "Controller\n(Rest Adapter)" as Controller
participant "CalculateChancesService\n(Use Case)" as Service
participant "ChancesCalculator" as Calculator
participant "JpaRepositoryAdapter\n(Outbound Port)" as Adapter
database PostgresSQL

== Request Chances ==

Player -> Controller : POST /api/blackjack/chances/{gameId}
Controller -> Service : calculateChances(query)
Service -> Adapter : retrieveGame(gameId)

alt game found
    Adapter -> PostgresSQL : SQL Query(gameId)
    PostgresSQL -> Adapter : Game
    Adapter -> Service : Game

    alt game running
    Service -> Calculator : calculateChances(playerHand, dealerHand)
    Calculator -> Service : Chances
    Service -> Controller : Chances
    Controller -> Player : 200 OK + Response

    else game over
        Service -> Controller : Error
        Controller -> Player : 400 Bad Request
    end

alt game not found
    PostgresSQL -> Adapter : Not Found
    Adapter -> Service : Error
    Service -> Controller : Error
    Controller -> Player : 404 Not Found

end

@enduml
