@startuml
title API Endpoint /api/blackjack/chances
actor Player

participant "Controller\n(Rest Adapter)" as Controller
participant "CalculateChances\n(Use Case)" as UseCase
participant "GameService\n(Application Service)" as Service
participant "Game\n(Domain Model)" as Domain

== Request Chances ==

Player -> Controller : POST /api/blackjack/chances\n{ playerHand, dealerHand }
Controller -> Controller : validateRequest()

alt correct request
    Controller -> UseCase : getChances(playerHand, dealerHand)
    UseCase -> Service : getChances(playerHand, dealerHand)
    Service -> Domain : calculateHitChances(playerHand, dealerHand)
    Domain --> Domain : performCalculations
    Domain --> Service : hit_chances
    Service --> Domain : calculateStandChances(playerHand, dealerHand)
    Domain --> Domain : performCalculations
    Domain --> Service : stand_chances
    Service --> UseCase : chancesDTO\n{ hit_chances, stand_chances }
    UseCase --> Controller : chancesDTO\n{ hit_chances, stand_chances }
    Controller --> Player : 200 OK + chances JSON

else wrong payload syntax
    Controller -> Player : 400 Bad Request
end

@enduml
